language: php

dist: trusty

# Note: behat compatibility fix
# See https://github.com/silverstripe/silverstripe-asset-admin/pull/711
sudo: required
group: deprecated-2017Q4

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - tidy
  firefox: "31.0"

env:
  global:
    - DB=MYSQL
    - COMPOSER_ROOT_VERSION=1.2.x-dev
    - DISPLAY=":99"
    - XVFBARGS=":99 -ac -screen 0 1024x768x16"
    - TRAVIS_NODE_VERSION="6"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DB=PGSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 5.6
      env: DB=MYSQL BEHAT_TEST=1
    - php: 7.0
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.1
      env: DB=MYSQL PDO=1
    - php: 5.6
      env: NPM_TEST=1

before_script:
# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - echo 'memory_limit = 2048M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer
  - composer validate
  - composer require --prefer-dist --no-update silverstripe/recipe-cms:1.2.x-dev
  - if [[ $DB == PGSQL ]]; then composer require --prefer-dist --no-update silverstripe/postgresql:2.0.x-dev; fi
  - if [[ $DB == SQLITE ]]; then composer require --prefer-dist --no-update silverstripe/sqlite3:2.0.x-dev; fi
  - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

# Start behat services
  - if [[ $BEHAT_TEST ]]; then mkdir artifacts; fi
  - if [[ $BEHAT_TEST ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/selenium-server-standalone > artifacts/selenium.log 2>&1 &); fi
  - if [[ $BEHAT_TEST ]]; then (vendor/bin/serve --bootstrap-file vendor/silverstripe/cms/tests/behat/serve-bootstrap.php &> artifacts/serve.log &); fi

# Install NPM dependencies
  - if [[ $NPM_TEST ]]; then nvm install $TRAVIS_NODE_VERSION && npm install -g yarn && yarn install --network-concurrency 1 && yarn run build; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit tests/php; fi
  - if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi
  - if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi
  - if [[ $NPM_TEST ]]; then yarn run lint; fi
  - if [[ $BEHAT_TEST ]]; then vendor/bin/behat @campaign-admin; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi

after_failure:
  - if [[ $BEHAT_TEST ]]; then php vendor/silverstripe/framework/tests/behat/travis-upload-artifacts.php --if-env BEHAT_TEST,ARTIFACTS_BUCKET,ARTIFACTS_KEY,ARTIFACTS_SECRET --target-path $TRAVIS_REPO_SLUG/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID --artifacts-base-url https://s3.amazonaws.com/$ARTIFACTS_BUCKET/ --artifacts-path ./artifacts/; fi
